import { StyleSheet } from "react-native";



const styles = StyleSheet.create({
  main: {
    flexGrow: 1,
    flexDirection: "column",
    padding: 15,
    backgroundColor: "white",
  },
  container: {
    marginTop: 50,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  backLocate: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    width: 62,
    justifyContent: "space-between",
  },
  nameHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: 150,
  },
  topButtonContainer: {
    width: 361,
    marginTop: 30,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  topButtons: {
    borderWidth: 1,
    borderColor: "#D3D3D3",
    width: 112,
    height: 32,
    borderRadius: 6,
    padding: 8,
    alignItems: "center",
  },
  topButtonsText: {
    fontFamily: "Quicksand-Reg",
    fontSize: 12,
  },
  VAContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 25,
    marginBottom: 25,
  },
  VAHeader: {
    fontFamily: "Quicksand-SemiBold",
    fontSize: 32,
  },
  starContainer: {
    flexDirection: "row",
    width: 124,
    height: 24,
    alignItems: "center",
    justifyContent: "space-evenly",
    padding: 8,
  },
  starSize: {
    width: 17,
    height: 17,
  },
  selectDate: {
    fontFamily: "Quicksand-Med",
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 10,
  },
  calendar: {
    marginBottom: 5,
    marginTop: 5,
    borderRadius: 9,
    paddingLeft: 25,
    paddingRight: 25,
    shadowColor: "gray",
    shadowOffset: { width: 2, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    width: 361,
    height: 373,
  },
  availTeeTimes: {
    fontFamily: "Quicksand-Med",
    fontSize: 16,
    lineHeight: 24,
    marginTop: 25,
    marginBottom: 10,
  },
  AVTContainer: {
    flexDirection: "column",
    marginBottom: 200,
  },
  AVTCards: {
    flexDirection: "column",
    justifyContent: "space-between",
    height: 40,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D3D3D3",
    marginBottom: 10,
  },
  AVTCardsSelected: {
    flexDirection: "column",
    justifyContent: "space-between",
    height: 96,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D3D3D3",
    backgroundColor: "#2FDA7426",
    marginBottom: 10,
  },
  AVTCardsGray: {
    flexDirection: "column",
    justifyContent: "space-between",
    height: 40,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 16,
    backgroundColor: "#D3D3D3",
    marginBottom: 10,
  },
  AVTCircleGray: {
    width: 24,
    height: 24,
    borderRadius: 25,
    backgroundColor: "#AFAFAF",
  },
  AVTTextGray: {
    fontFamily: "Quicksand-Med",
    fontSize: 16,
    lineHeight: 24,
    color: "#AFAFAF",
  },
  AVTCircle: {
    width: 24,
    height: 24,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: "#D3D3D3",
  },
  AVTCircleGreen: {
    width: 24,
    height: 24,
    borderRadius: 25,
    backgroundColor: "#2FDA74",
  },
  AVTText: {
    fontFamily: "Quicksand-Med",
    fontSize: 16,
    lineHeight: 24,
  },
  confirmTeeTime: {
    backgroundColor: "#2FDA74",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 8,
    borderRadius: 8,
  },
  confirmTeeTimeText: {
    color: "white",
    fontFamily: "Quicksand-SemiBold",
    fontSize: 16,
    lineHeight: 24,
  },
});



export default styles;