



const startingRoundObj = [
  {
    id: 1,
    image: require("../../../assets/Golf/Course1.png"),
    par: 4,
    distance: "250",
    wind: "5 mph",
    tip: "On Hole 1, a well-placed tee shot to the right can open up a favorable angle to attack the pin."
  },
  {
    id: 2,
    image: require("../../../assets/Golf/Course2.png"),
    par: 4,
    distance: "210",
    wind: "6 mph",
    tip: "For Hole 2, position your drive favoring the left side for a clearer approach to the green.",
  },
  {
    id: 3,
    image: require("../../../assets/Golf/Course3.png"),
    par: 3,
    distance: "330",
    wind: "7 mph",
    tip: "On Hole 3, a precise tee shot to the center sets up an ideal angle for the second shot.",
  },
  {
    id: 4,
    image: require("../../../assets/Golf/Course4.png"),
    par: 4,
    distance: "230",
    wind: "8 mph",
    tip: "For Hole 4, consider laying up short of the fairway bunkers to ensure a clear approach.",
  },
  {
    id: 5,
    image: require("../../../assets/Golf/Course5.png"),
    par: 4,
    distance: "240",
    wind: "8 mph",
    tip: "On Hole 5, aim for the right side of the fairway to avoid challenging hazards on the left.",
  },
  {
    id: 6,
    image: require("../../../assets/Golf/Course1.png"),
    par: 4,
    distance: "350",
    wind: "6 mph",
    tip: "For Hole 6, a well-placed tee shot to the left provides a better angle for the approach shot.",
  },
  {
    id: 7,
    image: require("../../../assets/Golf/Course2.png"),
    par: 3,
    distance: "160",
    wind: "8 mph",
    tip: "On Hole 7, avoid the fairway bunker on the right by aiming slightly left off the tee.",
  },
  {
    id: 8,
    image: require("../../../assets/Golf/Course3.png"),
    par: 3,
    distance: "170",
    wind: "5 mph",
    tip: "For Hole 8, play your tee shot to the right to avoid trouble on the left side of the fairway.",
  },
  {
    id: 9,
    image: require("../../../assets/Golf/Course4.png"),
    par: 4,
    distance: "180",
    wind: "6 mph",
    tip: "On Hole 9, position your drive favoring the left side to open up a better view of the green.",
  },
  {
    id: 10,
    image: require("../../../assets/Golf/Course5.png"),
    par: 4,
    distance: "190",
    wind: "8 mph",
    tip: "On Hole 10, aim your tee shot slightly right to avoid the fairway bunkers on the left.",
  },
  {
    id: 11,
    image: require("../../../assets/Golf/Course1.png"),
    par: 4,
    distance: "200",
    wind: "7 mph",
    tip: "For Hole 11, consider laying up short of the water hazard to ensure a safe approach to the green.",
  },
  {
    id: 12,
    image: require("../../../assets/Golf/Course2.png"),
    par: 4,
    distance: "210",
    wind: "4 mph",
    tip: "On Hole 12, favor the left side off the tee to avoid trouble on the right and set up a better angle.",
  },
  {
    id: 13,
    image: require("../../../assets/Golf/Course3.png"),
    par: 4,
    distance: "220",
    wind: "5 mph",
    tip: "For Hole 13, play your tee shot to the right side of the fairway to avoid trees on the left.",
  },
  {
    id: 14,
    image: require("../../../assets/Golf/Course4.png"),
    par: 4,
    distance: "230",
    wind: "4 mph",
    tip: "On Hole 14, aim for the center of the fairway to set up a clear approach shot to the green.",
  },
  {
    id: 15,
    image: require("../../../assets/Golf/Course5.png"),
    par: 4,
    distance: "240",
    wind: "3 mph",
    tip: "For Hole 15, consider a conservative tee shot to avoid the water hazard on the left side.",
  },
  {
    id: 16,
    image: require("../../../assets/Golf/Course1.png"),
    par: 4,
    distance: "250",
    wind: "5 mph",
    tip: "On Hole 16, aim your drive down the right side to avoid bunkers and trees on the left.",
  },
  {
    id: 17,
    image: require("../../../assets/Golf/Course2.png"),
    par: 4,
    distance: "260",
    wind: "7 mph",
    tip: "For Hole 17, play your tee shot to the left side of the fairway to avoid trouble on the right.",
  },
  {
    id: 18,
    image: require("../../../assets/Golf/Course3.png"),
    par: 4,
    distance: "270",
    wind: "8 mph",
    tip: "On Hole 18, position your drive favoring the right side to avoid bunkers and trees on the left.",
  },
];

export default startingRoundObj;
